GAME_NAME = "BOBBY'S MONEY MADNESS"
WINDOW_CAPTION = "Bobby's Money Madness"
DEBUG_ENABLED = True

SCREEN_WIDTH = 512
SCREEN_HEIGHT = 288
SCREEN_SIZE = SCREEN_WIDTH, SCREEN_HEIGHT

WINDOW_WIDTH = 1024
WINDOW_HEIGHT = 576
WINDOW_SIZE = WINDOW_WIDTH, WINDOW_HEIGHT

FPS = 60

FONTS_PATH = "../fonts"
SOUNDS_PATH = "../audio/fx"
MUSIC_PATH = "../audio/music"
GRAPHICS_PATH = "../graphics"
WORLD_DATA_PATH = "../bobby.ldtk"
BASE_PATH = "../"
ANIMATIONS_PATH = "../animations"

DEFAULT_FONT = "default3.otf"

DEBUG_START_IN_STATE = "title_screen"
